### ISSUE TITLE
Compile error when using object spread alongside other props

### ISSUE THREAD

**Issue by alexlande** [philpl/react-live#2]
👋 

Noticed this today-- when using object spread to pass props to an element, along with other standard props, you hit a bublé compile error.

#### Input

```js
() => {
  const someProps = { className: 'heading' };

  return (
    <h3 {...someProps} id='test'>
      So functional. Much wow!
    </h3>
  )
}
```

#### Error

```
CompileError: Mixed JSX attributes ending in spread requires specified objectAssign option with 'Object.assign' or polyfill helper. (5:3)
1 : () => {
2 :   const someProps = { className: 'heading' };
3 : 
4 :   return (
5 :     <h3 {...someProps} id='test'
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

#### Fix

bublé needs the `objectAssign` option to be specified in order to compile this correctly. Not sure what the best way to handle that would be. A few options:

1. `objectAssign: 'Object.assign'` - use native Object.assign, forcing consumers to polyfill it if necessary.
2. `objectAssign: '_.assign'` - Use Lodash or another assign/extend module. This feels like a little bit of an overstep on a library's part to me, but it would have the nice benefit of "just working" without a user having to think about it or even being aware of it.
3. `objectAssign: this.props.assignFunc` - Allow users to pass their own assign in. Flexible, but additional API and passing the function around is a little messy.

**Comment by philpl** [comment]
Cheers, Alex! 😄 

Is this looking good to you? It should avoid duplicating the dependency and the polyfill in most environments (babel). https://github.com/philpl/react-live/pull/3

**Comment by alexlande** [comment]
🙇  I dig it!
